# SPDX-FileCopyrightText:  Open Energy Transition gGmbH
#
# SPDX-License-Identifier: AGPL-3.0-or-later

version = 1
SPDX-PackageName = "efuels-supply-potentials"
SPDX-PackageSupplier = "Open Energy Transition"
SPDX-PackageDownloadLocation = "https://github.com/open-energy-transition/efuels-supply-potentials"

[[annotations]]
path = "data/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "Open Energy Transition gGmbH"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = "data/airport_data/airports.csv"
precedence = "aggregate"
SPDX-FileCopyrightText = "OurAirports (public domain, https://ourairports.com/data/)"
SPDX-License-Identifier = "Unlicense"

[[annotations]]
path = "data/airport_data/fuel_jf.csv"
precedence = "aggregate"
SPDX-FileCopyrightText = "U.S. Energy Information Administration"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "data/airport_data/T100_Domestic_Market_and_Segment_Data_-3591723781169319541.csv"
precedence = "aggregate"
SPDX-FileCopyrightText = "U.S. Department of Transportation, Bureau of Transportation Statistics"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "data/demand_projections/*.csv"
precedence = "aggregate"
SPDX-FileCopyrightText = "National Renewable Energy Laboratory (Alliance), U.S. Department of Energy"
SPDX-License-Identifier = "LicenseRef-NREL-Standard"

[[annotations]]
path = "data/industry_data/ethanolcapacity.xlsx"
precedence = "aggregate"
SPDX-FileCopyrightText = "U.S. Energy Information Administration"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ".github/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "Open Energy Transition gGmbH"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ".gitmodules"
precedence = "aggregate"
SPDX-FileCopyrightText = "Open Energy Transition gGmbH"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ".gitignore"
precedence = "aggregate"
SPDX-FileCopyrightText = "Open Energy Transition gGmbH"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ".gitattributes"
precedence = "aggregate"
SPDX-FileCopyrightText = "Open Energy Transition gGmbH"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "notebooks/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "Open Energy Transition gGmbH"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = "doc/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "Open Energy Transition gGmbH"
SPDX-License-Identifier = "AGPL-3.0-or-later"
